server:
  port: 7788
  ssl:
    enabled: false
    certificate: /etc/letsencrypt/live/api.teda.uz/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/api.teda.uz/privkey.pem
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ibrat_club
#    url: jdbc:postgresql://185.185.80.245/tedauzbot
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
telegram:
  bot:
    #   username: Uzb_Namaz_Times_bot
    #   token: 5082104093:AAEtEN22_VScHuRU7mgdvI8H-1p6v8hn8KU
    username: ibratclub_bot
    token: 5927728152:AAExhfEpagD__0D9A6b_qJs56SuXV06oZ-8
    id: 1
page:
  size: 20
