server:
  port: 88
spring:
  datasource:
    #    url: jdbc:postgresql://185.185.80.245/our_system
    url: jdbc:postgresql://localhost:5432/ibrat_club
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  main:
    lazy-initialization: true
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
page:
  size: 20
jwt:
  secretKey: turgun1970
  expireDate: 864000000
debug: false
